2025-01-23 16:07:20,308 INFO    MainThread:748520 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2025-01-23 16:07:20,308 INFO    MainThread:748520 [wandb_setup.py:_flush():76] Configure stats pid to 748520
2025-01-23 16:07:20,308 INFO    MainThread:748520 [wandb_setup.py:_flush():76] Loading settings from /common/home/hg343/.config/wandb/settings
2025-01-23 16:07:20,309 INFO    MainThread:748520 [wandb_setup.py:_flush():76] Loading settings from /common/home/hg343/Research/accelerate_combo_option/src/wandb/settings
2025-01-23 16:07:20,309 INFO    MainThread:748520 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2025-01-23 16:07:20,309 INFO    MainThread:748520 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'src/single_stock_frontier_data_preprocessor.py', 'program_abspath': '/common/home/hg343/Research/accelerate_combo_option/src/single_stock_frontier_data_preprocessor.py', 'program': '/common/home/hg343/Research/accelerate_combo_option/src/single_stock_frontier_data_preprocessor.py'}
2025-01-23 16:07:20,309 INFO    MainThread:748520 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-01-23 16:07:20,309 INFO    MainThread:748520 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-01-23 16:07:20,309 INFO    MainThread:748520 [wandb_init.py:_log_setup():520] Logging user logs to /common/home/hg343/Research/accelerate_combo_option/src/wandb/run-20250123_160720-2lmz1dn3/logs/debug.log
2025-01-23 16:07:20,309 INFO    MainThread:748520 [wandb_init.py:_log_setup():521] Logging internal logs to /common/home/hg343/Research/accelerate_combo_option/src/wandb/run-20250123_160720-2lmz1dn3/logs/debug-internal.log
2025-01-23 16:07:20,310 INFO    MainThread:748520 [wandb_init.py:init():560] calling init triggers
2025-01-23 16:07:20,310 INFO    MainThread:748520 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'output_file': 'single_frontier.pkl', 'market_stream': '../data/', 'wandb_project': 'expediating_comb_financial_market_matching', 'wandb_entity': 'single_stock_frontier_data', 'offset': False}
2025-01-23 16:07:20,310 INFO    MainThread:748520 [wandb_init.py:init():610] starting backend
2025-01-23 16:07:20,311 INFO    MainThread:748520 [wandb_init.py:init():614] setting up manager
2025-01-23 16:07:20,315 INFO    MainThread:748520 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-23 16:07:20,317 INFO    MainThread:748520 [wandb_init.py:init():622] backend started and connected
2025-01-23 16:07:20,325 INFO    MainThread:748520 [wandb_init.py:init():711] updated telemetry
2025-01-23 16:07:20,345 INFO    MainThread:748520 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2025-01-23 16:07:20,451 ERROR   MainThread:748520 [wandb_init.py:init():770] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2025-01-23 16:07:20,451 ERROR   MainThread:748520 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/common/home/hg343/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/common/home/hg343/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2025-01-23 16:07:21,491 WARNING MsgRouterThr:748520 [router.py:message_loop():77] message_loop has been closed
