2025-01-23 15:53:01,013 INFO    MainThread:727877 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2025-01-23 15:53:01,013 INFO    MainThread:727877 [wandb_setup.py:_flush():76] Configure stats pid to 727877
2025-01-23 15:53:01,013 INFO    MainThread:727877 [wandb_setup.py:_flush():76] Loading settings from /common/home/hg343/.config/wandb/settings
2025-01-23 15:53:01,014 INFO    MainThread:727877 [wandb_setup.py:_flush():76] Loading settings from /common/home/hg343/Research/accelerate_combo_option/src/wandb/settings
2025-01-23 15:53:01,014 INFO    MainThread:727877 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-01-23 15:53:01,014 INFO    MainThread:727877 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-01-23 15:53:01,014 INFO    MainThread:727877 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'src/single_stock_frontier_data_preprocessor.py', 'program_abspath': '/common/home/hg343/Research/accelerate_combo_option/src/single_stock_frontier_data_preprocessor.py', 'program': '/common/home/hg343/Research/accelerate_combo_option/src/single_stock_frontier_data_preprocessor.py'}
2025-01-23 15:53:01,015 INFO    MainThread:727877 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-01-23 15:53:01,015 INFO    MainThread:727877 [wandb_init.py:_log_setup():520] Logging user logs to /common/home/hg343/Research/accelerate_combo_option/src/wandb/run-20250123_155301-wdxhn7lq/logs/debug.log
2025-01-23 15:53:01,015 INFO    MainThread:727877 [wandb_init.py:_log_setup():521] Logging internal logs to /common/home/hg343/Research/accelerate_combo_option/src/wandb/run-20250123_155301-wdxhn7lq/logs/debug-internal.log
2025-01-23 15:53:01,016 INFO    MainThread:727877 [wandb_init.py:init():560] calling init triggers
2025-01-23 15:53:01,016 INFO    MainThread:727877 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2025-01-23 15:53:01,016 INFO    MainThread:727877 [wandb_init.py:init():610] starting backend
2025-01-23 15:53:01,017 INFO    MainThread:727877 [wandb_init.py:init():614] setting up manager
2025-01-23 15:53:01,022 INFO    MainThread:727877 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-23 15:53:01,024 INFO    MainThread:727877 [wandb_init.py:init():622] backend started and connected
2025-01-23 15:53:01,034 INFO    MainThread:727877 [wandb_init.py:init():711] updated telemetry
2025-01-23 15:53:01,053 INFO    MainThread:727877 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2025-01-23 15:53:01,151 ERROR   MainThread:727877 [wandb_init.py:init():770] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2025-01-23 15:53:01,151 ERROR   MainThread:727877 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/common/home/hg343/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/common/home/hg343/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2025-01-23 15:53:02,190 WARNING MsgRouterThr:727877 [router.py:message_loop():77] message_loop has been closed
